### ISSUE TITLE
Operation returned an invalid status code 'Badrequest'

### ISSUE THREAD

**Issue by Ypf485** [sql-bi/Pbi-PushDataset#10]
I followed all the documentation of Installing the tool and also created app on AAD with following the instruction on how to build Service Principal application to use Power BI services can you give me more insights. Please and Thank you.

**Comment by Ypf485** [comment]
![badrequest](https://user-images.githubusercontent.com/94969424/171734985-f35844db-3847-4e7e-b791-820e2582b323.PNG)

**Comment by marcosqlbi** [comment]
There could be several reasons:
- invalid security
- Invalid model
- other errors in the code
Are you able to debug the C# code of the component? I'm not sure how to get more diagnostic information with the current build.

**Comment by Ypf485** [comment]
Thanks for the reply
I have tested the model in C# using the other tools and overnight i was able to find why i am getting the error so that is solve

**Comment by Ypf485** [comment]
But i am also facing problem in update-PublishDataset could you explain what -READFROMWROKSPACE means?

**Comment by marcosqlbi** [comment]
It is a parameter that specifies from which dataset to extract the data for the initial population of the real-time dataset.

**Comment by nkuppili** [comment]
@Ypf485  are you able figure out the solution? I am facing same issue with my model 

@marcosqlbi 

`
** PUBLISH model **
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Operation returned an invalid status code 'BadRequest')
 ---> Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.PowerBI.Api.DatasetsOperations.PostDatasetInGroupWithHttpMessagesAsync(Guid groupId, CreateDatasetRequest dataset, Nullable`1 defaultRetentionPolicy, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.PowerBI.Api.DatasetsOperationsExtensions.PostDatasetInGroupAsync(IDatasetsOperations operations, Guid groupId, CreateDatasetRequest dataset, Nullable`1 defaultRetentionPolicy, CancellationToken cancellationToken)
   at Sqlbi.PbiPushDataset.PbiConnection.CreatePushDataset(FileInfo model, Guid groupId, String datasetName, Boolean overwriteExistingDataset, Boolean fifoPolicy, Action`1 unsupportedMeasureAction, Action`1 unsupportedRelationshipAction) in C:\Users\MarcoRusso\source\repos\Pbi-PushDataset\Sqlbi.PbiPushDataset\PbiConnection.cs:line 280
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Sqlbi.PbiPushTools.CommandLine.Publish(FileInfo model, String principal, String secret, String tenant, String group, String datasetName, String datasetId) in C:\Users\MarcoRusso\source\repos\Pbi-PushDataset\PbiPushTools\CommandLine.cs:line 42
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()`

**Comment by marcosqlbi** [comment]
@nkuppili your error seems different, do you have relationships like many-to-many or bidirectional filters? There seems to be an error about an unsupported relationship type.

**Comment by nkuppili** [comment]
> @nkuppili your error seems different, do you have relationships like many-to-many or bidirectional filters? There seems to be an error about an unsupported relationship type.

Yes we had both directions, Let me change to "One Directional" relation and try again. I will keep you posted.

**Comment by hoanghce** [comment]
Cannot install it

**Comment by marcosqlbi** [comment]
@hoanghce can you provide more details?
